<template><h1 id="wordpress通过代码添加自定义固定链接" tabindex="-1"><a class="header-anchor" href="#wordpress通过代码添加自定义固定链接" aria-hidden="true">#</a> WordPress通过代码添加自定义固定链接</h1>
<p>有时是安装了一些插件，比如问答型、文档型等，插件往往会自定义一些新内容类型，如：question，docs。这时候WordPress后台设置的固定链接对这些类型的内容就不起作用了，所以这时就得自定义固定链接，这里以安装了DW Question &amp; Answer和weDocs插件为例。</p>
<h4 id="设置内容显示链接" tabindex="-1"><a class="header-anchor" href="#设置内容显示链接" aria-hidden="true">#</a> 设置内容显示链接</h4>
<p>在列表中显示的链接</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">custom_my_link</span><span class="token punctuation">(</span> <span class="token parameter">$link<span class="token punctuation">,</span> $post <span class="token operator">=</span> <span class="token number">0</span></span> <span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span> $post<span class="token operator">-</span><span class="token operator">></span>post_type <span class="token operator">==</span> <span class="token string">'dwqa-question'</span> <span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">home_url</span><span class="token punctuation">(</span> <span class="token string">'question/'</span> <span class="token punctuation">.</span> $post<span class="token operator">-</span><span class="token operator">></span><span class="token constant">ID</span> <span class="token punctuation">.</span><span class="token string">'.html'</span> <span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token keyword">else</span> <span class="token keyword">if</span><span class="token punctuation">(</span>$post<span class="token operator">-</span><span class="token operator">></span>post_type <span class="token operator">==</span> <span class="token string">'docs'</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">home_url</span><span class="token punctuation">(</span> <span class="token string">'docs/'</span> <span class="token punctuation">.</span> $post<span class="token operator">-</span><span class="token operator">></span><span class="token constant">ID</span> <span class="token punctuation">.</span><span class="token string">'.html'</span> <span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> $link<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token function">add_filter</span><span class="token punctuation">(</span><span class="token string">'post_type_link'</span><span class="token punctuation">,</span> <span class="token string">'custom_my_link'</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><h4 id="解析固定链接" tabindex="-1"><a class="header-anchor" href="#解析固定链接" aria-hidden="true">#</a> 解析固定链接</h4>
<p>从列表中点击的链接需要解析才能正确获取的内容</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">custom_my_rewrites_init</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token function">add_rewrite_rule</span><span class="token punctuation">(</span><span class="token string">'question/([0-9]+)?.html$'</span><span class="token punctuation">,</span><span class="token string">'index.php?post_type=dwqa-question&amp;p=$matches[1]'</span><span class="token punctuation">,</span><span class="token string">'top'</span> <span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token function">add_rewrite_rule</span><span class="token punctuation">(</span><span class="token string">'docs/([0-9]+)?.html$'</span><span class="token punctuation">,</span><span class="token string">'index.php?post_type=docs&amp;p=$matches[1]'</span><span class="token punctuation">,</span><span class="token string">'top'</span> <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token function">add_action</span><span class="token punctuation">(</span> <span class="token string">'init'</span><span class="token punctuation">,</span> <span class="token string">'custom_my_rewrites_init'</span> <span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>以上代码都添加的主题的functions.php中，完成后需要重新在WordPress后台设置下固定链接，否则会出现404错误</p>
</template>
