<template><h1 id="typecho-免插件生成文章目录" tabindex="-1"><a class="header-anchor" href="#typecho-免插件生成文章目录" aria-hidden="true">#</a> Typecho 免插件生成文章目录</h1>
<p>迁移到 typecho 一段时间了，整体感觉虽然没有 WordPress 插件多，但够简洁易学习，能用简单的方式实现想要的功能，还是非常棒的。这不想实现一个文章目录的功能，大概搜索了下，也有相应的解决插件和代码，这里小编根据自己的需求，把网上的代码做了部分修改，功能函数独立放在 functions.php 中</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token doc-comment comment">/**
 * 为文章标题添加锚点
 * <span class="token keyword">@param</span> <span class="token parameter">$content</span>
 * <span class="token keyword">@return</span> string|string[]|null
 */</span>
<span class="token keyword">function</span> <span class="token function">createTocIndex</span><span class="token punctuation">(</span><span class="token parameter">$content</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    $tocCount <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> <span class="token function">preg_replace_callback</span><span class="token punctuation">(</span><span class="token string">'/&lt;h([1-3])(.*?)>(.*?)&lt;\/h\1>/i'</span><span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">$obj</span><span class="token punctuation">)</span> <span class="token function">use</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token operator">&amp;</span>$tocCount</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        $tocCount<span class="token operator">++</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token string">'&lt;h'</span> <span class="token punctuation">.</span> $obj<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span> <span class="token punctuation">.</span> $obj<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span> <span class="token punctuation">.</span> <span class="token string">'>&lt;a name="index-'</span> <span class="token punctuation">.</span> $tocCount <span class="token punctuation">.</span> <span class="token string">'">&lt;/a>'</span> <span class="token punctuation">.</span> $obj<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span> <span class="token punctuation">.</span> <span class="token string">'&lt;/h'</span> <span class="token punctuation">.</span> $obj<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span> <span class="token punctuation">.</span> <span class="token string">'>'</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span> $content<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token doc-comment comment">/**
 * 生成文章目录
 * <span class="token keyword">@param</span> <span class="token parameter">$content</span>
 */</span>
<span class="token keyword">function</span> <span class="token function">createTocTree</span><span class="token punctuation">(</span><span class="token parameter">$content</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    $tocArr <span class="token operator">=</span> <span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    $tocCount <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
    <span class="token function">preg_replace_callback</span><span class="token punctuation">(</span><span class="token string">'/&lt;h([1-3])(.*?)>(.*?)&lt;\/h\1>/i'</span><span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">$obj</span><span class="token punctuation">)</span> <span class="token function">use</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token operator">&amp;</span>$tocArr<span class="token punctuation">,</span> <span class="token operator">&amp;</span>$tocCount</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        $tocCount<span class="token operator">++</span><span class="token punctuation">;</span>
        $tocArr<span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'text'</span> <span class="token operator">=></span> <span class="token function">trim</span><span class="token punctuation">(</span><span class="token function">strip_tags</span><span class="token punctuation">(</span>$obj<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'depth'</span> <span class="token operator">=></span> $obj<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">'count'</span> <span class="token operator">=></span> $tocCount<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span> $content<span class="token punctuation">)</span><span class="token punctuation">;</span>
    $tocTree <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>$tocArr<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        $tocTree <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span>
        $prevDepth <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span>
        $nextDepth <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token function">foreach</span> <span class="token punctuation">(</span><span class="token parameter">$tocArr <span class="token keyword">as</span> $tocItem</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            $tocDepth <span class="token operator">=</span> $tocItem<span class="token punctuation">[</span><span class="token string">'depth'</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>$prevDepth<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">if</span> <span class="token punctuation">(</span>$tocDepth <span class="token operator">==</span> $prevDepth<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    $tocTree <span class="token punctuation">.</span><span class="token operator">=</span> <span class="token string">'&lt;/li>'</span><span class="token punctuation">;</span>
                <span class="token punctuation">}</span> <span class="token function">elseif</span> <span class="token punctuation">(</span><span class="token parameter">$tocDepth <span class="token operator">></span> $prevDepth</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    $nextDepth<span class="token operator">++</span><span class="token punctuation">;</span>
                    $tocTree <span class="token punctuation">.</span><span class="token operator">=</span> <span class="token string">'&lt;ul class="widget-list">'</span><span class="token punctuation">;</span>
                <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                    $nextDepth2 <span class="token operator">=</span> <span class="token punctuation">(</span>$nextDepth <span class="token operator">></span> <span class="token punctuation">(</span>$prevDepth <span class="token operator">-</span> $tocDepth<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">?</span> <span class="token punctuation">(</span>$prevDepth <span class="token operator">-</span> $tocDepth<span class="token punctuation">)</span> <span class="token operator">:</span> $nextDepth<span class="token punctuation">;</span>
                    <span class="token keyword">if</span> <span class="token punctuation">(</span>$nextDepth2<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                        <span class="token keyword">for</span> <span class="token punctuation">(</span>$i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> $i <span class="token operator">&lt;</span> $nextDepth2<span class="token punctuation">;</span> $i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                            $tocTree <span class="token punctuation">.</span><span class="token operator">=</span> <span class="token string">'&lt;/li>&lt;/ul>'</span><span class="token punctuation">;</span>
                            $nextDepth<span class="token operator">--</span><span class="token punctuation">;</span>
                        <span class="token punctuation">}</span>
                    <span class="token punctuation">}</span>
                    $tocTree <span class="token punctuation">.</span><span class="token operator">=</span> <span class="token string">'&lt;/li>'</span><span class="token punctuation">;</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span>
            $tocTree <span class="token punctuation">.</span><span class="token operator">=</span> <span class="token string">'&lt;li>&lt;a href="#index-'</span> <span class="token punctuation">.</span> $tocItem<span class="token punctuation">[</span><span class="token string">'count'</span><span class="token punctuation">]</span> <span class="token punctuation">.</span> <span class="token string">'">'</span> <span class="token punctuation">.</span> $tocItem<span class="token punctuation">[</span><span class="token string">'text'</span><span class="token punctuation">]</span> <span class="token punctuation">.</span> <span class="token string">'&lt;/a>'</span><span class="token punctuation">;</span>
            $prevDepth <span class="token operator">=</span> $tocItem<span class="token punctuation">[</span><span class="token string">'depth'</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">for</span> <span class="token punctuation">(</span>$i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> $i <span class="token operator">&lt;=</span> $nextDepth<span class="token punctuation">;</span> $i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            $tocTree <span class="token punctuation">.</span><span class="token operator">=</span> <span class="token string">'&lt;/li>'</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> $tocTree<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre></div><p>使用方式跟网上的差不多，在需要生成目录的地方调用</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span><span class="token operator">?</span>php echo <span class="token function">createTocTree</span><span class="token punctuation">(</span>$<span class="token keyword">this</span><span class="token operator">-</span><span class="token operator">></span>content<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token operator">?</span><span class="token operator">></span>
</code></pre></div><p>显示生成锚点内容的地方调用</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span><span class="token operator">?</span>php echo <span class="token function">createTocIndex</span><span class="token punctuation">(</span>$<span class="token keyword">this</span><span class="token operator">-</span><span class="token operator">></span>content<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token operator">?</span><span class="token operator">></span>
</code></pre></div><p>大概就是这样了，显示效果可以参考本网站“文档”分类中的文章</p>
<p>参考：<a href="http://www.wusail.com/blog/index.php/27.html" target="_blank" rel="noopener noreferrer">http://www.wusail.com/blog/index.php/27.html<OutboundLink/></a></p>
<hr>
<blockquote>
<p><strong>更新：以上使用的是 php 实现的，下面使用 js 来实现的</strong></p>
</blockquote>
<p>梳理下大致流程，首先在 sidebar.php 增加文章目录存放的 div 代码</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span><span class="token operator">?</span>php <span class="token keyword">if</span><span class="token punctuation">(</span>$<span class="token keyword">this</span><span class="token operator">-</span><span class="token operator">></span>type<span class="token operator">==</span><span class="token string">'post'</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token operator">?</span><span class="token operator">></span>
    <span class="token operator">&lt;</span>section <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"widget sticky"</span> id<span class="token operator">=</span><span class="token string">"tocTree"</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>h3 <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"widget-title"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">?</span>php <span class="token function">_e</span><span class="token punctuation">(</span><span class="token string">'文章目录'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token operator">?</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>h3<span class="token operator">></span>
        <span class="token operator">&lt;</span>ul <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"widget-list"</span><span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">/</span>ul<span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>section<span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">?</span>php endif<span class="token punctuation">;</span> <span class="token operator">?</span><span class="token operator">></span>  
</code></pre></div><p>然后使用 css 固定下，增加一个 .sticky 的样式</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">/*sticky*/</span>
<span class="token punctuation">.</span>sticky <span class="token punctuation">{</span>
    position<span class="token operator">:</span> <span class="token operator">-</span>webkit<span class="token operator">-</span>sticky<span class="token punctuation">;</span>
    position<span class="token operator">:</span> sticky<span class="token punctuation">;</span>
    top<span class="token operator">:</span><span class="token number">0</span><span class="token punctuation">;</span>
    font<span class="token operator">-</span>size<span class="token operator">:</span> <span class="token number">.92857</span>em<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token punctuation">.</span>sticky <span class="token punctuation">.</span>widget<span class="token operator">-</span>list<span class="token punctuation">{</span>
    overflow<span class="token operator">-</span>y<span class="token operator">:</span> auto<span class="token punctuation">;</span>
    max<span class="token operator">-</span>height<span class="token operator">:</span> <span class="token number">400</span>px<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre></div><p>最后就是核心的 js 代码了</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">if</span> <span class="token punctuation">(</span>document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'secondary'</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'secondary'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>style<span class="token punctuation">.</span>height <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'main'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>scrollHeight <span class="token operator">+</span> <span class="token string">'px'</span><span class="token punctuation">;</span>
    <span class="token comment">//生成文章目录</span>
    <span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> index <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token keyword">let</span> depth <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
        <span class="token keyword">let</span> tocTreeHtml <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span>
        <span class="token keyword">let</span> tocTreeObj <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'tocTree'</span><span class="token punctuation">)</span>
        <span class="token keyword">let</span> postContentObj <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'main'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'.post-content'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        postContentObj<span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> postContentObj<span class="token punctuation">.</span>innerHTML<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">&lt;h([1-6])(.*?)>(.*?)&lt;\/h\1></span><span class="token regex-delimiter">/</span><span class="token regex-flags">ig</span></span><span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">match<span class="token punctuation">,</span> num<span class="token punctuation">,</span> attrs<span class="token punctuation">,</span> html</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            index<span class="token operator">++</span><span class="token punctuation">;</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>depth <span class="token operator">&lt;</span> num<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">if</span> <span class="token punctuation">(</span>index <span class="token operator">></span> <span class="token number">1</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    tocTreeHtml <span class="token operator">+=</span> <span class="token string">'&lt;/li>&lt;li>&lt;ul class="widget-list">&lt;li>&lt;a href="#index-'</span> <span class="token operator">+</span> index <span class="token operator">+</span> <span class="token string">'">'</span> <span class="token operator">+</span> html <span class="token operator">+</span> <span class="token string">'&lt;/a>'</span><span class="token punctuation">;</span>
                <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                    tocTreeHtml <span class="token operator">+=</span> <span class="token string">'&lt;li>&lt;a href="#index-'</span> <span class="token operator">+</span> index <span class="token operator">+</span> <span class="token string">'">'</span> <span class="token operator">+</span> html <span class="token operator">+</span> <span class="token string">'&lt;/a>'</span><span class="token punctuation">;</span>
                <span class="token punctuation">}</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>depth <span class="token operator">==</span> num<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                tocTreeHtml <span class="token operator">+=</span> <span class="token string">'&lt;/li>&lt;li>&lt;a href="#index-'</span> <span class="token operator">+</span> index <span class="token operator">+</span> <span class="token string">'">'</span> <span class="token operator">+</span> html <span class="token operator">+</span> <span class="token string">'&lt;/a>'</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>depth <span class="token operator">></span> num<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                tocTreeHtml <span class="token operator">+=</span> <span class="token string">'&lt;/li>'</span> <span class="token operator">+</span> <span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Array</span><span class="token punctuation">(</span>depth <span class="token operator">-</span> num <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">'&lt;/ul>&lt;/li>'</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'&lt;li>&lt;a href="#index-'</span> <span class="token operator">+</span> index <span class="token operator">+</span> <span class="token string">'">'</span> <span class="token operator">+</span> html <span class="token operator">+</span> <span class="token string">'&lt;/a>'</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            depth <span class="token operator">=</span> num<span class="token punctuation">;</span>
            <span class="token keyword">return</span> <span class="token string">'&lt;h'</span> <span class="token operator">+</span> num <span class="token operator">+</span> attrs <span class="token operator">+</span> <span class="token string">' id="index-'</span> <span class="token operator">+</span> <span class="token punctuation">(</span>index<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'">'</span> <span class="token operator">+</span> html <span class="token operator">+</span> <span class="token string">'&lt;/h'</span> <span class="token operator">+</span> num <span class="token operator">+</span> <span class="token string">'>'</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>tocTreeHtml<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            tocTreeObj<span class="token punctuation">.</span>style<span class="token punctuation">.</span>display <span class="token operator">=</span> <span class="token string">'block'</span><span class="token punctuation">;</span>
            tocTreeObj<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'.widget-list'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> tocTreeHtml<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//文章目录跟随内容滚动</span>
    <span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">let</span> tocIndexNode <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">querySelectorAll</span><span class="token punctuation">(</span><span class="token string">'[id^="index"]'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">let</span> tocTreeListObj <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">'tocTree'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'.widget-list'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>tocIndexNode<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            window<span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span><span class="token string">'scroll'</span><span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">let</span> scrollTop <span class="token operator">=</span> document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>scrollTop<span class="token punctuation">;</span>
                <span class="token keyword">let</span> windowHeight <span class="token operator">=</span> window<span class="token punctuation">.</span>innerHeight<span class="token punctuation">;</span>
                tocIndexNode<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">item<span class="token punctuation">,</span> index<span class="token punctuation">,</span> tocIndexNode</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                    <span class="token keyword">let</span> tocNameObj <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'[href="#'</span> <span class="token operator">+</span> item<span class="token punctuation">.</span>attributes<span class="token punctuation">[</span><span class="token string">'id'</span><span class="token punctuation">]</span><span class="token punctuation">.</span>value <span class="token operator">+</span> <span class="token string">'"]'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                    <span class="token keyword">if</span> <span class="token punctuation">(</span>tocIndexNode<span class="token punctuation">[</span>Math<span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span>index <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">,</span> tocIndexNode<span class="token punctuation">.</span>length <span class="token operator">-</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">.</span>offsetTop <span class="token operator">-</span> scrollTop <span class="token operator">></span> <span class="token number">0</span> <span class="token operator">&amp;&amp;</span> item<span class="token punctuation">.</span>offsetTop <span class="token operator">-</span> scrollTop <span class="token operator">&lt;</span> windowHeight<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                        tocNameObj<span class="token punctuation">.</span>style<span class="token punctuation">.</span>fontWeight <span class="token operator">=</span> <span class="token string">'bolder'</span><span class="token punctuation">;</span>
                        tocTreeListObj<span class="token punctuation">.</span><span class="token function">scrollTo</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> tocNameObj<span class="token punctuation">.</span>offsetTop <span class="token operator">-</span> tocTreeListObj<span class="token punctuation">.</span>offsetHeight<span class="token operator">/</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
                    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                        tocNameObj<span class="token punctuation">.</span>style<span class="token punctuation">.</span>fontWeight <span class="token operator">=</span> <span class="token string">'normal'</span><span class="token punctuation">;</span>
                    <span class="token punctuation">}</span>
                <span class="token punctuation">}</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre></div><p>以上 js 是根据 typecho 默认主题写的，实现了文章目录，并自动跟随内容滚动</p>
</template>
