<template><h1 id="typecho-文章部分加密和显示标题" tabindex="-1"><a class="header-anchor" href="#typecho-文章部分加密和显示标题" aria-hidden="true">#</a> Typecho 文章部分加密和显示标题</h1>
<p>typecho 部分功能使用确实不是很方面，需要修改源码才行，比如加密文章竟然不显示标题，这也是崩溃了，只好修改下源码</p>
<p><strong>显示标题</strong></p>
<p>编辑文件 var/Widget/Abstract/Contents.php，大概在 744 行左右，找到：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$value<span class="token punctuation">[</span><span class="token string">'title'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">_t</span><span class="token punctuation">(</span><span class="token string">'此内容被密码保护'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><p>改成下面的这个，也就是注释注释掉这行就好了。</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//$value['title'] = _t('此内容被密码保护'); </span>
</code></pre></div><p><strong>文章部分加密</strong></p>
<p>这里用到了 “&lt;--more--&gt;” 作为分割，“&lt;--more--&gt;” 的内容加密，也是修改 var/Widget/Abstract/Contents.php 文件：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$value<span class="token punctuation">[</span><span class="token string">'text'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">explode</span><span class="token punctuation">(</span><span class="token string">'&lt;!--more-->'</span><span class="token punctuation">,</span> $<span class="token keyword">this</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">markdown</span><span class="token punctuation">(</span>$value<span class="token punctuation">[</span><span class="token string">'text'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span> <span class="token comment">//前面是新增的部分代码</span>
<span class="token string">'&lt;form class="protected" action="'</span> <span class="token punctuation">.</span> $<span class="token keyword">this</span><span class="token operator">-</span><span class="token operator">></span>security<span class="token operator">-</span><span class="token operator">></span><span class="token function">getTokenUrl</span><span class="token punctuation">(</span>$value<span class="token punctuation">[</span><span class="token string">'permalink'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
                <span class="token punctuation">.</span> <span class="token string">'" method="post">'</span> <span class="token punctuation">.</span>
            <span class="token string">'&lt;p class="word">'</span> <span class="token punctuation">.</span> <span class="token function">_t</span><span class="token punctuation">(</span><span class="token string">'请输入密码访问'</span><span class="token punctuation">)</span> <span class="token punctuation">.</span> <span class="token string">'&lt;/p>'</span> <span class="token punctuation">.</span>
            '<span class="token operator">&lt;</span>p<span class="token operator">></span><span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"password"</span> <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"text"</span> name<span class="token operator">=</span><span class="token string">"protectPassword"</span> <span class="token operator">/</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"submit"</span> <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"submit"</span> value<span class="token operator">=</span><span class="token string">"' . _t('提交') . '"</span> <span class="token operator">/</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>' <span class="token punctuation">.</span>
            <span class="token string">'&lt;/form>'</span><span class="token punctuation">;</span>
</code></pre></div><p>下面是演示效果，输入密码：123456，查看</p>
<blockquote>
<p>这里是加密的部分内容...</p>
</blockquote>
</template>
