<template><h1 id="解决ueditor插入第三方视频网站通用代码的问题" tabindex="-1"><a class="header-anchor" href="#解决ueditor插入第三方视频网站通用代码的问题" aria-hidden="true">#</a> 解决ueditor插入第三方视频网站通用代码的问题</h1>
<p>百度ueditor编辑器使用非常广泛，由此衍生的各种定制化的编辑器也非常多，如微信公众号文章编辑器等都是基于ueditor编辑器开发的，但官方维护的是通用的pc编辑器，有些格式不适应移动h5页面显示，比如图片自适应，不能插入第三方网站视频通用代码等。因此，也需要进行必要的修改来满足定制化的需求。</p>
<blockquote>
<p>所谓第三方视频网站通用代码，就是视频网站提供分享功能时，可选择html代码，通过代码等，通用代码可以兼容手机播放，比如在iPhone，ipad上播放</p>
</blockquote>
<p>需要满足的功能：</p>
<ul>
<li>支持插入视频功能</li>
<li>视频播放兼容手机播放,如iPhone</li>
</ul>
<h3 id="支持插入视频功能" tabindex="-1"><a class="header-anchor" href="#支持插入视频功能" aria-hidden="true">#</a> 支持插入视频功能</h3>
<p>基于ueditor编辑器强大的可定制化的功能，支持插入视频功能非常简单<br>
在<strong>ueditor/ueditor.config.js</strong>的<strong>toolbars</strong>添加 <strong>insertvideo</strong>即可</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//工具栏上的所有的功能按钮和下拉框，可以在new编辑器的实例时选择自己需要的重新定义</span>
<span class="token punctuation">,</span> toolbars<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token operator">...</span><span class="token string">'insertvideo'</span><span class="token punctuation">,</span><span class="token punctuation">]</span><span class="token punctuation">]</span> 
</code></pre></div><h3 id="视频播放兼容手机播放" tabindex="-1"><a class="header-anchor" href="#视频播放兼容手机播放" aria-hidden="true">#</a> 视频播放兼容手机播放</h3>
<p>这里主要是插入第三方视频播放器，而且为了兼容手机播放，会使用第三方视频网站通用代码（可以在视频播放页-分享-通用代码中获取），一般格式如下：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>iframe frameborder<span class="token operator">=</span><span class="token string">"0"</span> width<span class="token operator">=</span><span class="token string">"640"</span> height<span class="token operator">=</span><span class="token string">"498"</span> src<span class="token operator">=</span><span class="token string">"https://v.qq.com/iframe/player.html?vid=y0016tj0qvh&amp;tiny=0&amp;auto=0"</span> allowfullscreen<span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>iframe<span class="token operator">></span> 
</code></pre></div><p>ueditor编辑器视频网址默认的不支持插入iframe格式，这里需要修改下源码<br>
路径：<strong>ueditor/dialogs/video/video.js</strong> ，修改的地方如下：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">...</span>
<span class="token doc-comment comment">/**
 * 将单个视频信息插入编辑器中
 * 修改：处理通用视频代码iframe   awei 2017-09-11
 */</span>
<span class="token keyword">function</span> <span class="token function">insertSingle</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">var</span> width <span class="token operator">=</span> $<span class="token constant">G</span><span class="token punctuation">(</span><span class="token string">"videoWidth"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
        height <span class="token operator">=</span> $<span class="token constant">G</span><span class="token punctuation">(</span><span class="token string">"videoHeight"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
        url<span class="token operator">=</span>$<span class="token constant">G</span><span class="token punctuation">(</span><span class="token string">'videoUrl'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>value<span class="token punctuation">,</span>
        align <span class="token operator">=</span> <span class="token function">findFocus</span><span class="token punctuation">(</span><span class="token string">"videoFloat"</span><span class="token punctuation">,</span><span class="token string">"name"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span>url<span class="token punctuation">)</span> <span class="token keyword">return</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span> <span class="token operator">!</span><span class="token function">checkNum</span><span class="token punctuation">(</span> <span class="token punctuation">[</span>width<span class="token punctuation">,</span> height<span class="token punctuation">]</span> <span class="token punctuation">)</span> <span class="token punctuation">)</span> <span class="token keyword">return</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token doc-comment comment">/**处理通用视频代码iframe   awei 2017-09-11 **/</span>
    url <span class="token operator">=</span> utils<span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^&lt;iframe</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token keyword">var</span> conUrl <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">src="[^s"]+</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
            conUrl <span class="token operator">=</span> url<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">src="[^s"]+</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">substr</span><span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">var</span> newIframe <span class="token operator">=</span> editor<span class="token punctuation">.</span>document<span class="token punctuation">.</span><span class="token function">createElement</span><span class="token punctuation">(</span><span class="token string">"iframe"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">var</span> div<span class="token punctuation">;</span>
        newIframe<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">"src"</span><span class="token punctuation">,</span><span class="token operator">/</span>http<span class="token operator">:</span><span class="token operator">/</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">|https:</span><span class="token regex-delimiter">/</span></span><span class="token comment">//ig.test(conUrl) ? conUrl : "http://"+conUrl);</span>
        <span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">+</span><span class="token punctuation">[</span><span class="token punctuation">.</span><span class="token punctuation">]</span><span class="token operator">?</span>d<span class="token operator">*</span>$<span class="token operator">/</span>g<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span> width<span class="token punctuation">.</span>value <span class="token punctuation">)</span> <span class="token operator">?</span> newIframe<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">"width"</span><span class="token punctuation">,</span>width<span class="token punctuation">.</span>value<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token string">""</span><span class="token punctuation">;</span>
        <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^[1-9]+[.]?d*$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span> height<span class="token punctuation">.</span>value <span class="token punctuation">)</span> <span class="token operator">?</span> newIframe<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">"height"</span><span class="token punctuation">,</span>height<span class="token punctuation">.</span>value<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token string">""</span><span class="token punctuation">;</span>
        <span class="token comment">//newIframe.setAttribute("scrolling","no");</span>
        newIframe<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">"frameborder"</span><span class="token punctuation">,</span><span class="token string">"0"</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        newIframe<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">"allowfullscreen"</span><span class="token punctuation">,</span><span class="token string">"allowfullscreen"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        newIframe<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">"align"</span><span class="token punctuation">,</span>align<span class="token punctuation">)</span><span class="token punctuation">;</span>
        div <span class="token operator">=</span> editor<span class="token punctuation">.</span>document<span class="token punctuation">.</span><span class="token function">createElement</span><span class="token punctuation">(</span><span class="token string">"div"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        div<span class="token punctuation">.</span><span class="token function">appendChild</span><span class="token punctuation">(</span>newIframe<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">//alert(div.innerHTML);</span>
        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>div<span class="token punctuation">.</span>innerHTML<span class="token punctuation">)</span><span class="token punctuation">;</span>
        editor<span class="token punctuation">.</span><span class="token function">execCommand</span><span class="token punctuation">(</span><span class="token string">"inserthtml"</span><span class="token punctuation">,</span>div<span class="token punctuation">.</span>innerHTML<span class="token punctuation">,</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span><span class="token doc-comment comment">/** -end 处理通用视频代码iframe   awei 2017-09-11 **/</span>
        editor<span class="token punctuation">.</span><span class="token function">execCommand</span><span class="token punctuation">(</span><span class="token string">'insertvideo'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>
            url<span class="token operator">:</span> <span class="token function">convert_url</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">,</span>
            width<span class="token operator">:</span> width<span class="token punctuation">.</span>value<span class="token punctuation">,</span>
            height<span class="token operator">:</span> height<span class="token punctuation">.</span>value<span class="token punctuation">,</span>
            align<span class="token operator">:</span> align
        <span class="token punctuation">}</span><span class="token punctuation">,</span> isModifyUploadVideo <span class="token operator">?</span> <span class="token string">'upload'</span><span class="token operator">:</span><span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token comment">///**处理通用视频代码iframe   awei 2017-09-11 **/</span>
<span class="token punctuation">}</span>
<span class="token operator">...</span>
<span class="token doc-comment comment">/**
 * 根据url生成视频预览
 * 修改：处理通用视频代码iframe   awei 2017-09-11
 * <span class="token keyword">@param</span> <span class="token parameter">url</span>
 */</span>
<span class="token keyword">function</span> <span class="token function">createPreviewVideo</span><span class="token punctuation">(</span><span class="token parameter">url</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span> <span class="token operator">!</span>url <span class="token punctuation">)</span><span class="token keyword">return</span><span class="token punctuation">;</span>
    <span class="token doc-comment comment">/** 处理通用视频代码iframe   awei 2017-09-11 **/</span>
    url <span class="token operator">=</span> utils<span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^&lt;iframe</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token keyword">var</span> conUrl <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">src="[^s"]+</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
            conUrl <span class="token operator">=</span> url<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">src="[^s"]+</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">substr</span><span class="token punctuation">(</span><span class="token number">5</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        $<span class="token constant">G</span><span class="token punctuation">(</span><span class="token string">"preview"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> <span class="token string">'&lt;div class="previewMsg">&lt;span>'</span><span class="token operator">+</span>lang<span class="token punctuation">.</span>urlError<span class="token operator">+</span><span class="token string">'&lt;/span>&lt;/div>'</span><span class="token operator">+</span>
        <span class="token string">'&lt;iframe class="previewVideo"'</span> <span class="token operator">+</span>
            <span class="token string">' src="'</span><span class="token operator">%</span><span class="token number">20</span><span class="token operator">+</span><span class="token operator">%</span><span class="token number">20</span>conUrl<span class="token operator">%</span><span class="token number">20</span><span class="token operator">+</span><span class="token operator">%</span><span class="token number">20</span><span class="token string">'"'</span> <span class="token operator">+</span>
            <span class="token string">' width="'</span> <span class="token operator">+</span> <span class="token number">420</span>  <span class="token operator">+</span> <span class="token string">'"'</span> <span class="token operator">+</span>
            <span class="token string">' height="'</span> <span class="token operator">+</span> <span class="token number">280</span>  <span class="token operator">+</span> <span class="token string">'"'</span> <span class="token operator">+</span>
            <span class="token string">' frameborder=0 allowfullscreen>'</span> <span class="token operator">+</span>
        <span class="token string">'&lt;/iframe>'</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span><span class="token doc-comment comment">/** -end 处理通用视频代码iframe   awei 2017-09-11 **/</span>
        <span class="token keyword">var</span> conUrl <span class="token operator">=</span> <span class="token function">convert_url</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">;</span>
        conUrl <span class="token operator">=</span> utils<span class="token punctuation">.</span><span class="token function">unhtmlForUrl</span><span class="token punctuation">(</span>conUrl<span class="token punctuation">)</span><span class="token punctuation">;</span>
        $<span class="token constant">G</span><span class="token punctuation">(</span><span class="token string">"preview"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> <span class="token string">'&lt;div class="previewMsg">&lt;span>'</span><span class="token operator">+</span>lang<span class="token punctuation">.</span>urlError<span class="token operator">+</span><span class="token string">'&lt;/span>&lt;/div>'</span><span class="token operator">+</span>
        <span class="token string">'&lt;embed class="previewVideo" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"'</span> <span class="token operator">+</span>
            <span class="token string">' src="'</span><span class="token operator">%</span><span class="token number">20</span><span class="token operator">+</span><span class="token operator">%</span><span class="token number">20</span>conUrl<span class="token operator">%</span><span class="token number">20</span><span class="token operator">+</span><span class="token operator">%</span><span class="token number">20</span><span class="token string">'"'</span> <span class="token operator">+</span>
            <span class="token string">' width="'</span> <span class="token operator">+</span> <span class="token number">420</span>  <span class="token operator">+</span> <span class="token string">'"'</span> <span class="token operator">+</span>
            <span class="token string">' height="'</span> <span class="token operator">+</span> <span class="token number">280</span>  <span class="token operator">+</span> <span class="token string">'"'</span> <span class="token operator">+</span>
            <span class="token string">' wmode="transparent" play="true" loop="false" menu="false" allowscriptaccess="never" allowfullscreen="true" >'</span> <span class="token operator">+</span>
        <span class="token string">'&lt;/embed>'</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token comment">///** 处理通用视频代码iframe   awei 2017-09-11 **/</span>
<span class="token operator">...</span> 
</code></pre></div><p>大家可以自行比较下,绝对有区别,但是决不会影响ueditor的正常功能，但这里还需要比较重要的一步，添加过滤白名单<br>
在<strong>ueditor/ueditor.config.js</strong>的 <strong>whitList</strong> 添加白名单</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">// xss过滤白名单 名单来源: https://raw.githubusercontent.com/leizongmin/js-xss/master/lib/default.js</span>
<span class="token punctuation">,</span>whitList<span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>
    iframe<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">'src'</span><span class="token punctuation">,</span> <span class="token string">'class'</span><span class="token punctuation">,</span> <span class="token string">'height'</span><span class="token punctuation">,</span> <span class="token string">'width'</span><span class="token punctuation">,</span> <span class="token string">'max-width'</span><span class="token punctuation">,</span> <span class="token string">'max-height'</span><span class="token punctuation">,</span> <span class="token string">'align'</span><span class="token punctuation">,</span> <span class="token string">'frameborder'</span><span class="token punctuation">,</span> <span class="token string">'allowfullscreen'</span><span class="token punctuation">]</span>
<span class="token punctuation">}</span> 
</code></pre></div><p>到这里就大功告成了。</p>
</template>
