<template><h1 id="phaser-js-移动-适配-自适应的模式" tabindex="-1"><a class="header-anchor" href="#phaser-js-移动-适配-自适应的模式" aria-hidden="true">#</a> Phaser.js 移动（适配）自适应的模式</h1>
<p>固定模式，在 <code>Phaser</code>的<code>Game</code>构造函数中用像素值来定义游戏的长宽，例如下面的代码就是设置游戏的大小为<code>640 x 480</code>像素:</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> game <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Phaser<span class="token punctuation">.</span>Game</span><span class="token punctuation">(</span><span class="token number">640</span><span class="token punctuation">,</span> <span class="token number">480</span><span class="token punctuation">,</span> Phaser<span class="token punctuation">.</span><span class="token constant">AUTO</span><span class="token punctuation">,</span> <span class="token string">'container'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><p>百分比模式，也可以使用百分比来定义游戏画布的大小：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> game <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Phaser<span class="token punctuation">.</span>Game</span><span class="token punctuation">(</span><span class="token string">'100%'</span><span class="token punctuation">,</span> <span class="token string">'100%'</span><span class="token punctuation">,</span> Phaser<span class="token punctuation">.</span><span class="token constant">AUTO</span><span class="token punctuation">,</span> <span class="token string">'container'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><p>适配模式，可以在游戏代码任何位置设置游戏的适配模式，但建议只做一次设置，之后不再改变。缩放操作都是直接由<code>ScaleManager</code>来管理，如果有一个全局变量<code>game</code>，可以通过<code>game.scale</code>来操作。</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>game<span class="token punctuation">.</span>scale<span class="token punctuation">.</span>scaleMode <span class="token operator">=</span> Phaser<span class="token punctuation">.</span>ScaleManager<span class="token punctuation">.</span><span class="token constant">SHOW_ALL</span><span class="token punctuation">;</span>
</code></pre></div><p>参考：<a href="http://autoref.cn/2016/08/06/91/" target="_blank" rel="noopener noreferrer">http://autoref.cn/2016/08/06/91/<OutboundLink/></a></p>
</template>
