<template><h1 id="vuejs-常见问题" tabindex="-1"><a class="header-anchor" href="#vuejs-常见问题" aria-hidden="true">#</a> vuejs 常见问题</h1>
<p><RouterLink to="/learns/vuejs-faq/27125.html">v-show 和 v-if 的区别</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27127.html">为何在 v-for 中用 key</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27128.html">描述 Vue 组件生命周期（包括父子组件）</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27129.html">Vue 组件如何通讯（常见）</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27131.html">描述组件渲染和更新的过程</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27132.html">双向数据绑定 v-model 的实现原理</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27134.html">对 MVVM 的理解</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27137.html">computed 有何特点</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27138.html">为何组件 data 必须是一个函数？</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27139.html">ajax 请求应该放在哪个生命周期</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27141.html">如何将组件所有 props 传递给子组件？</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27142.html">如何自己实现 v-model</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27143.html">多个组件有相同的逻辑，如何抽离？</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27144.html">何时要使用异步组件？</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27145.html">何时需要使用 keep-alive ？</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27147.html">何时需要使用 beforeDestory ?</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27148.html">什么是作用域插槽</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27150.html">Vuex 中 action 和 mutation 有何区别</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27151.html">Vue-router 常用的路由模式</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27152.html">如何配置 Vue-router 异步加载</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27153.html">请 vnode 描述一个 DOM 结构</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27154.html">监听 data 变化的核心 API 是什么</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27156.html">Vue 如何监听数组变化</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27157.html">请描述响应式原理</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27158.html">diff 算法的时间复杂度</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27159.html">简述 diff 算法过程</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27161.html">Vue 为何是异步渲染，$nextTick 何用？</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27163.html">Vue 常见性能优化方式</RouterLink><br>
<RouterLink to="/learns/vuejs-faq/27958.html">Vue 和 React 的区别</RouterLink></p>
</template>
