<template><h1 id="laravel-entrust中文说明" tabindex="-1"><a class="header-anchor" href="#laravel-entrust中文说明" aria-hidden="true">#</a> Laravel Entrust中文说明</h1>
<blockquote>
<p>GitHub：<a href="https://github.com/Zizaco/entrust" target="_blank" rel="noopener noreferrer">https://github.com/Zizaco/entrust<OutboundLink/></a></p>
</blockquote>
<p>Entrust为我们在Laravel中实现基于角色的权限管理（RBAC）提供了简洁灵活的方式。</p>
<p>如果您正在寻找Laravel 4版本，请查看<a href="https://github.com/Zizaco/entrust/tree/1.0" target="_blank" rel="noopener noreferrer">Branch 1.0<OutboundLink/></a>。它包含Laravel 4的最新版本。</p>
<h2 id="安装" tabindex="-1"><a class="header-anchor" href="#安装" aria-hidden="true">#</a> 安装</h2>
<p>在Laravel 5中安装Entrust，只需将以下内容添加到composer.json即可。然后运行<code>composer update</code>：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token string">"zizaco/entrust"</span><span class="token operator">:</span> <span class="token string">"5.2.x-dev"</span>
</code></pre></div><p>打开<code>config/app.php</code>并将以下内容添加到<code>providers</code>数组中：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>ZizacoEntrustEntrustServiceProvider<span class="token operator">:</span><span class="token operator">:</span><span class="token keyword">class</span><span class="token punctuation">,</span>
</code></pre></div><p>同样的在<code>config/app.php</code>添加以下内容<code>aliases</code>：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token string">'Entrust'</span>   <span class="token operator">=></span> ZizacoEntrustEntrustFacade<span class="token operator">:</span><span class="token operator">:</span><span class="token keyword">class</span><span class="token punctuation">,</span>
</code></pre></div><p>运行以下命令以发布程序包的配置文件<code>config/entrust.php</code>：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>php artisan vendor<span class="token operator">:</span>publish
</code></pre></div><p>打开<code>config/auth.php</code>并添加以下内容：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token string">'providers'</span> <span class="token operator">=></span> <span class="token punctuation">[</span>
    <span class="token string">'users'</span> <span class="token operator">=></span> <span class="token punctuation">[</span>
        <span class="token string">'driver'</span> <span class="token operator">=></span> <span class="token string">'eloquent'</span><span class="token punctuation">,</span>
        <span class="token string">'model'</span> <span class="token operator">=></span> NamespaceOfYourUserModelUser<span class="token operator">:</span><span class="token operator">:</span><span class="token keyword">class</span><span class="token punctuation">,</span>
        <span class="token string">'table'</span> <span class="token operator">=></span> <span class="token string">'users'</span><span class="token punctuation">,</span>
    <span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span><span class="token punctuation">,</span>
</code></pre></div><p>如果想要使用<a href="https://wpfaq.cn/archives/docs/20510#middleware" target="_blank" rel="noopener noreferrer">中间件<OutboundLink/></a>（需要Laravel 5.1或更高版本），还需要添加以下内容：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token string">'role'</span> <span class="token operator">=></span> izacoEntrustMiddlewareEntrustRole<span class="token operator">:</span><span class="token operator">:</span><span class="token keyword">class</span><span class="token punctuation">,</span>
<span class="token string">'permission'</span> <span class="token operator">=></span> izacoEntrustMiddlewareEntrustPermission<span class="token operator">:</span><span class="token operator">:</span><span class="token keyword">class</span><span class="token punctuation">,</span>
<span class="token string">'ability'</span> <span class="token operator">=></span> izacoEntrustMiddlewareEntrustAbility<span class="token operator">:</span><span class="token operator">:</span><span class="token keyword">class</span><span class="token punctuation">,</span>
</code></pre></div><p>到<code>app/Http/Kernel.php</code>的<code>routeMiddleware</code>数组中。</p>
<h2 id="配置" tabindex="-1"><a class="header-anchor" href="#配置" aria-hidden="true">#</a> 配置</h2>
<p>在配置文件<code>config/auth.php</code>中设置合适的值，Entrust会使用这些配置值来选择相应的用户表和模型类：</p>
<p>要进一步自定义表名和模型类命名空间，请编辑<code>config/entrust.php</code>。</p>
<h3 id="用户角色权限表" tabindex="-1"><a class="header-anchor" href="#用户角色权限表" aria-hidden="true">#</a> 用户角色权限表</h3>
<p>现在生成Entrust迁移文件：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>php artisan entrust<span class="token operator">:</span>migration 
</code></pre></div><p>它将生成类似<code>&lt;timestamp&gt;_entrust_setup_tables.php</code>迁移文件。您现在可以使用artisan migrate命令运行它：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>php artisan migrate 
</code></pre></div><p>执行迁移后，将生产四个新表：</p>
<ul>
<li><code>roles</code> – 存储角色</li>
<li><code>permissions</code> – 存储权限</li>
<li><code>role_user</code>– 存储角色和用户之间<a href="http://laravel.com/docs/4.2/eloquent#many-to-many" target="_blank" rel="noopener noreferrer">的多对多<OutboundLink/></a>关系</li>
<li><code>permission_role</code>– 存储角色和权限之间<a href="http://laravel.com/docs/4.2/eloquent#many-to-many" target="_blank" rel="noopener noreferrer">的多对多<OutboundLink/></a>关系</li>
</ul>
<h3 id="模型类" tabindex="-1"><a class="header-anchor" href="#模型类" aria-hidden="true">#</a> 模型类</h3>
<h4 id="角色" tabindex="-1"><a class="header-anchor" href="#角色" aria-hidden="true">#</a> 角色</h4>
<p>在<code>app/models/Role.php</code>里面创建Role模型，并使用以下示例：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span><span class="token operator">?</span>php namespace App<span class="token punctuation">;</span>
use ZizacoEntrustEntrustRole<span class="token punctuation">;</span>
<span class="token keyword">class</span> <span class="token class-name">Role</span> <span class="token keyword">extends</span> <span class="token class-name">EntrustRole</span>
<span class="token punctuation">{</span>
<span class="token punctuation">}</span> 
</code></pre></div><p>该<code>Role</code>模型有三个主要属性：</p>
<ul>
<li><code>name</code> – 角色的唯一名称，用于在应用程序层中查找角色信息。例如：“admin”，“owner”，“employee”。</li>
<li><code>display_name</code> – 人类可读的角色名称。非唯一的且是可选的。例如：“用户管理员”，“项目所有者”，“Widget Co.员工”。</li>
<li><code>description</code> – 更详细地说明角色的作用。也是可选的。</li>
</ul>
<p><code>display_name</code>和<code>description</code>是可选的; 他们的字段在数据库中可以为空。</p>
<h4 id="权限" tabindex="-1"><a class="header-anchor" href="#权限" aria-hidden="true">#</a> 权限</h4>
<p>在<code>app/models/Permission.php</code>创建Permission模型，并使用以下示例里面：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span><span class="token operator">?</span>php namespace App<span class="token punctuation">;</span>
use ZizacoEntrustEntrustPermission<span class="token punctuation">;</span>
<span class="token keyword">class</span> <span class="token class-name">Permission</span> <span class="token keyword">extends</span> <span class="token class-name">EntrustPermission</span>
<span class="token punctuation">{</span>
<span class="token punctuation">}</span> 
</code></pre></div><p>该<code>Permission</code>模型具有与<code>Role</code>模型相同的三个属性：</p>
<ul>
<li><code>name</code> – 权限的唯一名称，用于在应用程序层中查找权限信息。例如：“create-post”，“edit-user”，“post-payment”，“mailing-list-subscribe”。</li>
<li><code>display_name</code> – 人类可读的权限名称。非唯一的且是可选的。例如“创建帖子”，“编辑用户”，“邮寄付款”，“订阅邮件列表”。</li>
<li><code>description</code> – 对权限的更详细说明。</li>
</ul>
<p>一般来说，可以使用后两个属性来组成句子帮助说明权限，比如：“该权限<code>display_name</code>允许用户<code>description</code>。”</p>
<h4 id="用户" tabindex="-1"><a class="header-anchor" href="#用户" aria-hidden="true">#</a> 用户</h4>
<p>接下来，在现有<code>User</code>模型中使用<code>EntrustUserTrait</code> trait。例如：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span><span class="token operator">?</span>php
use ZizacoEntrustTraitsEntrustUserTrait<span class="token punctuation">;</span>
<span class="token keyword">class</span> <span class="token class-name">User</span> <span class="token keyword">extends</span> <span class="token class-name">Eloquent</span>
<span class="token punctuation">{</span>
    use EntrustUserTrait<span class="token punctuation">;</span> <span class="token comment">//添加EntrustUserTrait到User模型</span>
    <span class="token operator">...</span>
<span class="token punctuation">}</span> 
</code></pre></div><p>这将与<code>Role</code>模型建立关系，并<code>User</code>模型添加<code>roles()</code>，<code>hasRole($name)</code>，<code>withRole($name)</code>，<code>can($permission)</code>，和<code>ability($roles, $permissions, $options)</code>方法。</p>
<p>使用composer autoload更新自动加载</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>composer dump<span class="token operator">-</span>autoload 
</code></pre></div><h4 id="软删除" tabindex="-1"><a class="header-anchor" href="#软删除" aria-hidden="true">#</a> 软删除</h4>
<p>使用Entrust提供的迁移命令生成的关联关系表中默认使用了<code>onDelete('cascade')</code>以便父级记录被删除后移除其对应的关联关系。如果你由于某种原因不能在数据库中使用级联删除，那么可以在<code>EntrustRole</code>、<code>EntrustPermission</code>类以及<code>HasRole</code> trait提供的事件监听器中手动删除关联表中的记录。如果模型使用了软删除，那么当不小心误删除数据时，事件监听器将不会删除关联表数据。不过，由于Laravel事件监听器的局限性，所以暂时无法区分是调用<code>delete()</code>还是<code>forceDelete()</code>，基于这个原因，在你删除一个模型之前，必须手动删除所有关联数据（除非你的数据表使用了级联删除）：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$role <span class="token operator">=</span> Role<span class="token operator">:</span><span class="token operator">:</span><span class="token function">findOrFail</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 获取给定权限</span>
<span class="token comment">// 正常删除</span>
$role<span class="token operator">-</span><span class="token operator">></span><span class="token keyword">delete</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// This will work no matter what</span>
<span class="token comment">// 强制删除</span>
$role<span class="token operator">-</span><span class="token operator">></span><span class="token function">users</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">sync</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 删除关联数据</span>
$role<span class="token operator">-</span><span class="token operator">></span><span class="token function">perms</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">sync</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 删除关联数据</span>
$role<span class="token operator">-</span><span class="token operator">></span><span class="token function">forceDelete</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 不管透视表是否有级联删除都会生效</span>
</code></pre></div><h2 id="使用" tabindex="-1"><a class="header-anchor" href="#使用" aria-hidden="true">#</a> 使用</h2>
<h3 id="创建角色-权限" tabindex="-1"><a class="header-anchor" href="#创建角色-权限" aria-hidden="true">#</a> 创建角色/权限</h3>
<p>让我们从创建<code>Role</code>s和<code>Permission</code>s开始：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$owner <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Role</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
$owner<span class="token operator">-</span><span class="token operator">></span>name         <span class="token operator">=</span> <span class="token string">'owner'</span><span class="token punctuation">;</span>
$owner<span class="token operator">-</span><span class="token operator">></span>display_name <span class="token operator">=</span> <span class="token string">'Project Owner'</span><span class="token punctuation">;</span> <span class="token comment">// 可选</span>
$owner<span class="token operator">-</span><span class="token operator">></span>description  <span class="token operator">=</span> <span class="token string">'User is the owner of a given project'</span><span class="token punctuation">;</span> <span class="token comment">// 可选</span>
$owner<span class="token operator">-</span><span class="token operator">></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
$admin <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Role</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
$admin<span class="token operator">-</span><span class="token operator">></span>name         <span class="token operator">=</span> <span class="token string">'admin'</span><span class="token punctuation">;</span>
$admin<span class="token operator">-</span><span class="token operator">></span>display_name <span class="token operator">=</span> <span class="token string">'User Administrator'</span><span class="token punctuation">;</span> <span class="token comment">// 可选</span>
$admin<span class="token operator">-</span><span class="token operator">></span>description  <span class="token operator">=</span> <span class="token string">'User is allowed to manage and edit other users'</span><span class="token punctuation">;</span> <span class="token comment">// 可选</span>
$admin<span class="token operator">-</span><span class="token operator">></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>创建两个角色后，接下来让我们将它们分配给用户。由于有<code>HasRole</code> trait，这将很简单：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$user <span class="token operator">=</span> User<span class="token operator">:</span><span class="token operator">:</span><span class="token function">where</span><span class="token punctuation">(</span><span class="token string">'username'</span><span class="token punctuation">,</span> <span class="token string">'='</span><span class="token punctuation">,</span> <span class="token string">'michele'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">first</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 调用EntrustUserTrait提供的attachRole方法</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">attachRole</span><span class="token punctuation">(</span>$admin<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 参数可以是Role对象，数组或id</span>
<span class="token comment">// 或者也可以使用Eloquent原生的方法</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">roles</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">attach</span><span class="token punctuation">(</span>$admin<span class="token operator">-</span><span class="token operator">></span>id<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 只需传递id即可 </span>
</code></pre></div><p>现在我们只需要为这些角色添加权限：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$createPost <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Permission</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
$createPost<span class="token operator">-</span><span class="token operator">></span>name         <span class="token operator">=</span> <span class="token string">'create-post'</span><span class="token punctuation">;</span>
$createPost<span class="token operator">-</span><span class="token operator">></span>display_name <span class="token operator">=</span> <span class="token string">'Create Posts'</span><span class="token punctuation">;</span> <span class="token comment">// 可选</span>
<span class="token comment">// 允许用户...</span>
$createPost<span class="token operator">-</span><span class="token operator">></span>description  <span class="token operator">=</span> <span class="token string">'create new blog posts'</span><span class="token punctuation">;</span> <span class="token comment">// 可选</span>
$createPost<span class="token operator">-</span><span class="token operator">></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
$editUser <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Permission</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
$editUser<span class="token operator">-</span><span class="token operator">></span>name         <span class="token operator">=</span> <span class="token string">'edit-user'</span><span class="token punctuation">;</span>
$editUser<span class="token operator">-</span><span class="token operator">></span>display_name <span class="token operator">=</span> <span class="token string">'Edit Users'</span><span class="token punctuation">;</span> <span class="token comment">// 可选</span>
<span class="token comment">// 允许用户...</span>
$editUser<span class="token operator">-</span><span class="token operator">></span>description  <span class="token operator">=</span> <span class="token string">'edit existing users'</span><span class="token punctuation">;</span> <span class="token comment">// 可选</span>
$editUser<span class="token operator">-</span><span class="token operator">></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
$admin<span class="token operator">-</span><span class="token operator">></span><span class="token function">attachPermission</span><span class="token punctuation">(</span>$createPost<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 等价于  $admin->perms()->sync(array($createPost->id));</span>
$owner<span class="token operator">-</span><span class="token operator">></span><span class="token function">attachPermissions</span><span class="token punctuation">(</span><span class="token function">array</span><span class="token punctuation">(</span>$createPost<span class="token punctuation">,</span> $editUser<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 等价于  $owner->perms()->sync(array($createPost->id, $editUser->id)); </span>
</code></pre></div><h4 id="检查角色-权限" tabindex="-1"><a class="header-anchor" href="#检查角色-权限" aria-hidden="true">#</a> 检查角色&amp;权限</h4>
<p>现在我们可以通过以下方式检查角色和权限：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">hasRole</span><span class="token punctuation">(</span><span class="token string">'owner'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>   <span class="token comment">// false</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">hasRole</span><span class="token punctuation">(</span><span class="token string">'admin'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>   <span class="token comment">// true</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">can</span><span class="token punctuation">(</span><span class="token string">'edit-user'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>   <span class="token comment">// false</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">can</span><span class="token punctuation">(</span><span class="token string">'create-post'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// true </span>
</code></pre></div><p><code>hasRole()</code>并<code>can()</code>都可以接收数组形式的角色和权限进行检查：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">hasRole</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'owner'</span><span class="token punctuation">,</span> <span class="token string">'admin'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>       <span class="token comment">// true</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">can</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'edit-user'</span><span class="token punctuation">,</span> <span class="token string">'create-post'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// true </span>
</code></pre></div><p>默认情况下，如果用户存在任何一个角色或权限，该方法都将返回true。如果需要检查<strong>所有</strong>权限和角色，可以把true作为第二个参数传递相应方法：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">hasRole</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'owner'</span><span class="token punctuation">,</span> <span class="token string">'admin'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>             <span class="token comment">// true</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">hasRole</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'owner'</span><span class="token punctuation">,</span> <span class="token string">'admin'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>       <span class="token comment">// false, user does not have admin role</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">can</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'edit-user'</span><span class="token punctuation">,</span> <span class="token string">'create-post'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>       <span class="token comment">// true</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">can</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'edit-user'</span><span class="token punctuation">,</span> <span class="token string">'create-post'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// false, user does not have edit-user permission </span>
</code></pre></div><p><code>User</code>可以拥有任意数量的<code>Role</code>s，反之亦然。</p>
<p><code>Entrust</code>类提供了快捷方法<code>can()</code>和<code>hasRole()</code>来检查当前登录用户是否拥有指定角色和权限：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">hasRole</span><span class="token punctuation">(</span><span class="token string">'role-name'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">can</span><span class="token punctuation">(</span><span class="token string">'permission-name'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 等价于</span>
Auth<span class="token operator">:</span><span class="token operator">:</span><span class="token function">user</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">hasRole</span><span class="token punctuation">(</span><span class="token string">'role-name'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
Auth<span class="token operator">:</span><span class="token operator">:</span><span class="token function">user</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">can</span><span class="token punctuation">(</span><span class="token string">'permission-name'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>还可以通过通配符的方式来检查用户权限：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">// 匹配admin的任何权限</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">can</span><span class="token punctuation">(</span><span class="token string">"admin.*"</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// true</span>
<span class="token comment">// 匹配任何相关的users权限</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">can</span><span class="token punctuation">(</span><span class="token string">"*_users"</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// true </span>
</code></pre></div><p>要根据特定角色过滤用户，可以使用withRole() 查询作用域，例如检索所有管理员：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$admins <span class="token operator">=</span> User<span class="token operator">:</span><span class="token operator">:</span><span class="token function">withRole</span><span class="token punctuation">(</span><span class="token string">'admin'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 也可以是关联关系</span>
$company<span class="token operator">-</span><span class="token operator">></span><span class="token function">users</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">withRole</span><span class="token punctuation">(</span><span class="token string">'admin'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><h4 id="ability方法" tabindex="-1"><a class="header-anchor" href="#ability方法" aria-hidden="true">#</a> ability方法</h4>
<p>更高级的检查可以使用更好的<code>ability</code>方法。它包含三个参数（角色，权限，选项）：</p>
<ul>
<li><code>roles</code> 是一组要检查的角色。</li>
<li><code>permissions</code> 是一组要检查的权限。</li>
</ul>
<p>角色或权限变量可以是逗号分隔的字符串也可以是数组：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">ability</span><span class="token punctuation">(</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'admin'</span><span class="token punctuation">,</span> <span class="token string">'owner'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'create-post'</span><span class="token punctuation">,</span> <span class="token string">'edit-user'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 或者</span>
$user<span class="token operator">-</span><span class="token operator">></span><span class="token function">ability</span><span class="token punctuation">(</span><span class="token string">'admin,owner'</span><span class="token punctuation">,</span> <span class="token string">'create-post,edit-user'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>这将会检查用户是否拥有任意提供的角色和权限。在本例中将返回true，因为该用户属于<code>admin</code>角色并拥有<code>create-post</code>权限。</p>
<p>第三个参数是一个选项数组：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$options <span class="token operator">=</span> <span class="token function">array</span><span class="token punctuation">(</span>
    <span class="token string">'validate_all'</span> <span class="token operator">=></span> <span class="token boolean">true</span> <span class="token operator">|</span> <span class="token boolean">false</span> <span class="token punctuation">(</span>Default<span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token string">'return_type'</span>  <span class="token operator">=></span> boolean <span class="token operator">|</span> array <span class="token operator">|</span> <span class="token function">both</span> <span class="token punctuation">(</span>Default<span class="token operator">:</span> boolean<span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><ul>
<li><code>validate_all</code> 是一个布尔值，用于设置是否检查所有值，或者至少匹配一个角色或权限则返回true。</li>
<li><code>return_type</code> 用于指定返回布尔值、检查值数组还是两者都有。</li>
</ul>
<p>这是一个示例输出：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>$options <span class="token operator">=</span> <span class="token function">array</span><span class="token punctuation">(</span>
    <span class="token string">'validate_all'</span> <span class="token operator">=></span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token string">'return_type'</span> <span class="token operator">=></span> <span class="token string">'both'</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token function">list</span><span class="token punctuation">(</span>$validate<span class="token punctuation">,</span> $allValidations<span class="token punctuation">)</span> <span class="token operator">=</span> $user<span class="token operator">-</span><span class="token operator">></span><span class="token function">ability</span><span class="token punctuation">(</span>
    <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'admin'</span><span class="token punctuation">,</span> <span class="token string">'owner'</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'create-post'</span><span class="token punctuation">,</span> <span class="token string">'edit-user'</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    $options
<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token function">var_dump</span><span class="token punctuation">(</span>$validate<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// bool(false)</span>
<span class="token function">var_dump</span><span class="token punctuation">(</span>$allValidations<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// array(4) {</span>
<span class="token comment">//     ['role'] => bool(true)</span>
<span class="token comment">//     ['role_2'] => bool(false)</span>
<span class="token comment">//     ['create-post'] => bool(true)</span>
<span class="token comment">//     ['edit-user'] => bool(false)</span>
<span class="token comment">// } </span>
</code></pre></div><p><code>Entrust</code>类有一个快捷方法<code>ability()</code>来检查当前登录用户：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">ability</span><span class="token punctuation">(</span><span class="token string">'admin,owner'</span><span class="token punctuation">,</span> <span class="token string">'create-post,edit-user'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 等价于</span>
Auth<span class="token operator">:</span><span class="token operator">:</span><span class="token function">user</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">ability</span><span class="token punctuation">(</span><span class="token string">'admin,owner'</span><span class="token punctuation">,</span> <span class="token string">'create-post,edit-user'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><h3 id="blade模板" tabindex="-1"><a class="header-anchor" href="#blade模板" aria-hidden="true">#</a> Blade模板</h3>
<p>可以在Blade模板中使用上述对应的三个方法。直接把指令参数传递给相应的<code>Entrust</code>函数。</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>@<span class="token function">role</span><span class="token punctuation">(</span><span class="token string">'admin'</span><span class="token punctuation">)</span>
    <span class="token operator">&lt;</span>p<span class="token operator">></span>This is visible to users <span class="token keyword">with</span> the admin role<span class="token punctuation">.</span> Gets translated to
    Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">role</span><span class="token punctuation">(</span><span class="token string">'admin'</span><span class="token punctuation">)</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
@endrole
@<span class="token function">permission</span><span class="token punctuation">(</span><span class="token string">'manage-admins'</span><span class="token punctuation">)</span>
    <span class="token operator">&lt;</span>p<span class="token operator">></span>This is visible to users <span class="token keyword">with</span> the given permissions<span class="token punctuation">.</span> Gets translated to
    Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">can</span><span class="token punctuation">(</span><span class="token string">'manage-admins'</span><span class="token punctuation">)</span><span class="token punctuation">.</span> The @can directive is already taken by core
    laravel authorization <span class="token keyword">package</span><span class="token punctuation">,</span> hence the @permission directive instead<span class="token punctuation">.</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
@endpermission
@<span class="token function">ability</span><span class="token punctuation">(</span><span class="token string">'admin,owner'</span><span class="token punctuation">,</span> <span class="token string">'create-post,edit-user'</span><span class="token punctuation">)</span>
    <span class="token operator">&lt;</span>p<span class="token operator">></span>This is visible to users <span class="token keyword">with</span> the given abilities<span class="token punctuation">.</span> Gets translated to
    Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">ability</span><span class="token punctuation">(</span><span class="token string">'admin,owner'</span><span class="token punctuation">,</span> <span class="token string">'create-post,edit-user'</span><span class="token punctuation">)</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
@endability 
</code></pre></div><h3 id="中间件" tabindex="-1"><a class="header-anchor" href="#中间件" aria-hidden="true">#</a> 中间件</h3>
<p>可以使用中间件按权限或角色过滤路由和路由组</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>Route<span class="token operator">:</span><span class="token operator">:</span><span class="token function">group</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'prefix'</span> <span class="token operator">=></span> <span class="token string">'admin'</span><span class="token punctuation">,</span> <span class="token string">'middleware'</span> <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token string">'role:admin'</span><span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    Route<span class="token operator">:</span><span class="token operator">:</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'/'</span><span class="token punctuation">,</span> <span class="token string">'AdminController@welcome'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    Route<span class="token operator">:</span><span class="token operator">:</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'/manage'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">'middleware'</span> <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token string">'permission:manage-admins'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">'uses'</span> <span class="token operator">=></span> <span class="token string">'AdminController@manageAdmins'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>可以使用管道符号作为_OR_逻辑运算符：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token string">'middleware'</span> <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token string">'role:admin|root'</span><span class="token punctuation">]</span> 
</code></pre></div><p>要实现_AND_逻辑功能，只需使用多个中间件实例</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token string">'middleware'</span> <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token string">'role:owner'</span><span class="token punctuation">,</span> <span class="token string">'role:writer'</span><span class="token punctuation">]</span> 
</code></pre></div><p>对于更复杂的情况，可以使用<code>ability</code>中间件接受3个参数：roles，permissions，validate_all</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token string">'middleware'</span> <span class="token operator">=></span> <span class="token punctuation">[</span><span class="token string">'ability:admin|owner,create-post|edit-user,true'</span><span class="token punctuation">]</span> 
</code></pre></div><h3 id="路由过滤器的快捷方式" tabindex="-1"><a class="header-anchor" href="#路由过滤器的快捷方式" aria-hidden="true">#</a> 路由过滤器的快捷方式</h3>
<p>要按权限或角色过滤路由，可以在<code>app/Http/routes.php</code>中调用以下内容：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">// 只有拥有'create-post'权限对应角色的用户才能访问admin/post*</span>
Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">routeNeedsPermission</span><span class="token punctuation">(</span><span class="token string">'admin/post*'</span><span class="token punctuation">,</span> <span class="token string">'create-post'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 只有所有者才能访问admin/advanced*</span>
Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">routeNeedsRole</span><span class="token punctuation">(</span><span class="token string">'admin/advanced*'</span><span class="token punctuation">,</span> <span class="token string">'owner'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 第二个参数可以是数组，这样用户必须满足所有条件才能访问对应路由</span>
Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">routeNeedsPermission</span><span class="token punctuation">(</span><span class="token string">'admin/post*'</span><span class="token punctuation">,</span> <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'create-post'</span><span class="token punctuation">,</span> <span class="token string">'edit-comment'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">routeNeedsRole</span><span class="token punctuation">(</span><span class="token string">'admin/advanced*'</span><span class="token punctuation">,</span> <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'owner'</span><span class="token punctuation">,</span><span class="token string">'writer'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>这两种方法都可以接受第三个参数。如果第三个参数为null，则返回禁止访问默认调用<code>App::abort(403)</code>，否则返回第三个参数。所以这样可以使用它：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">routeNeedsRole</span><span class="token punctuation">(</span><span class="token string">'admin/advanced*'</span><span class="token punctuation">,</span> <span class="token string">'owner'</span><span class="token punctuation">,</span> Redirect<span class="token operator">:</span><span class="token operator">:</span><span class="token function">to</span><span class="token punctuation">(</span><span class="token string">'/home'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>此外，这两种方法还接受第四个参数。它默认为true并检查给定的所有角色/权限。如果将其设置为false，则只有当该用户的所有角色/权限都不满足时，该方法才会失败。对于要管理允许多个组访问的应用程序很有用。</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">// 如果用户拥有'create-post'、'edit-comment'其中之一或者两个权限都具备则可以访问</span>
Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">routeNeedsPermission</span><span class="token punctuation">(</span><span class="token string">'admin/post*'</span><span class="token punctuation">,</span> <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'create-post'</span><span class="token punctuation">,</span> <span class="token string">'edit-comment'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 如果用户是所有者、作者或者都具备则可以访问</span>
Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">routeNeedsRole</span><span class="token punctuation">(</span><span class="token string">'admin/advanced*'</span><span class="token punctuation">,</span> <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'owner'</span><span class="token punctuation">,</span><span class="token string">'writer'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 如果用户是‘owner’，‘writer’或两者的成员，或者用户具有‘create-post’，‘edit-comment’，他们将有权访问</span>
<span class="token comment">// 如果第4个参数为true，那么用户必须是角色的成员，必须拥有相应的权限</span>
Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">routeNeedsRoleOrPermission</span><span class="token punctuation">(</span>
    <span class="token string">'admin/advanced*'</span><span class="token punctuation">,</span>
    <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'owner'</span><span class="token punctuation">,</span> <span class="token string">'writer'</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">array</span><span class="token punctuation">(</span><span class="token string">'create-post'</span><span class="token punctuation">,</span> <span class="token string">'edit-comment'</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token keyword">null</span><span class="token punctuation">,</span>
    <span class="token boolean">false</span>
<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><h3 id="路由过滤器" tabindex="-1"><a class="header-anchor" href="#路由过滤器" aria-hidden="true">#</a> 路由过滤器</h3>
<p>只需使用Facade中的<code>can</code>和<code>hasRole</code>方法，就可以在过滤器中使用Entrust角色/权限：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>Route<span class="token operator">:</span><span class="token operator">:</span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token string">'manage_posts'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token comment">// check the current user</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">can</span><span class="token punctuation">(</span><span class="token string">'create-post'</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> Redirect<span class="token operator">:</span><span class="token operator">:</span><span class="token function">to</span><span class="token punctuation">(</span><span class="token string">'admin'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//只有用户对应角色拥有 'manage_posts' 权限才能访问任意 admin/post 路由</span>
Route<span class="token operator">:</span><span class="token operator">:</span><span class="token function">when</span><span class="token punctuation">(</span><span class="token string">'admin/post*'</span><span class="token punctuation">,</span> <span class="token string">'manage_posts'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>使用过滤器检查角色：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>Route<span class="token operator">:</span><span class="token operator">:</span><span class="token function">filter</span><span class="token punctuation">(</span><span class="token string">'owner_role'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
    <span class="token comment">// check the current user</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>Entrust<span class="token operator">:</span><span class="token operator">:</span><span class="token function">hasRole</span><span class="token punctuation">(</span><span class="token string">'Owner'</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        App<span class="token operator">:</span><span class="token operator">:</span><span class="token function">abort</span><span class="token punctuation">(</span><span class="token number">403</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 只有所有者才能访问 admin/advanced* 路由</span>
Route<span class="token operator">:</span><span class="token operator">:</span><span class="token function">when</span><span class="token punctuation">(</span><span class="token string">'admin/advanced*'</span><span class="token punctuation">,</span> <span class="token string">'owner_role'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>可以看到<code>Entrust::hasRole()</code>和<code>Entrust::can()</code>检查用户是否已登录，然后他/她是否具有该角色或权限。如果用户未登录，则返回也将是<code>false</code>。</p>
<h2 id="实例" tabindex="-1"><a class="header-anchor" href="#实例" aria-hidden="true">#</a> 实例</h2>
<h3 id="角色的增删改查" tabindex="-1"><a class="header-anchor" href="#角色的增删改查" aria-hidden="true">#</a> 角色的增删改查</h3>
<p>创建</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//关联新角色权限关系</span>
Role<span class="token operator">:</span><span class="token operator">:</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">all</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>permission<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    Role<span class="token operator">:</span><span class="token operator">:</span><span class="token function">attachPermissions</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>permission<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> 
</code></pre></div><p>修改</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//更新角色权限关系</span>
Role<span class="token operator">:</span><span class="token operator">:</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">all</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>permission<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    Role<span class="token operator">:</span><span class="token operator">:</span><span class="token function">savePermissions</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>permission<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> 
</code></pre></div><p>删除</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//由于存在外键约束，会自动同步删除角色权限关系</span>
Role<span class="token operator">:</span><span class="token operator">:</span><span class="token function">destroy</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>id<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>查询</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//查询角色拥有的权限</span>
Role<span class="token operator">:</span><span class="token operator">:</span><span class="token keyword">with</span><span class="token punctuation">(</span><span class="token string">'perms'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">find</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>id<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><h3 id="用户的增删改查" tabindex="-1"><a class="header-anchor" href="#用户的增删改查" aria-hidden="true">#</a> 用户的增删改查</h3>
<p>创建</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//关联角色</span>
User<span class="token operator">:</span><span class="token operator">:</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">all</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>role<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    User<span class="token operator">:</span><span class="token operator">:</span><span class="token function">roles</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">sync</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>role<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> 
</code></pre></div><p>修改</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//更新角色关系</span>
User<span class="token operator">:</span><span class="token operator">:</span><span class="token function">update</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">all</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>role<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    User<span class="token operator">:</span><span class="token operator">:</span><span class="token function">roles</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">sync</span><span class="token punctuation">(</span>$request<span class="token operator">-</span><span class="token operator">></span>role<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> 
</code></pre></div><p>删除</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//由于存在外键约束，会自动同步删除用户角色关系</span>
User<span class="token operator">:</span><span class="token operator">:</span><span class="token function">destroy</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>id<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>查询</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">//查询用户拥有的角色和权限</span>
User<span class="token operator">:</span><span class="token operator">:</span><span class="token keyword">with</span><span class="token punctuation">(</span><span class="token string">'roles.perms'</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span><span class="token function">find</span><span class="token punctuation">(</span><span class="token function">request</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-</span><span class="token operator">></span>id<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre></div><p>以上是参考，请根据具体业务逻辑发挥</p>
<h2 id="faq" tabindex="-1"><a class="header-anchor" href="#faq" aria-hidden="true">#</a> FAQ</h2>
<p>如果在执行迁移时遇到错误，如下所示：</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token constant">SQLSTATE</span><span class="token punctuation">[</span><span class="token constant">HY000</span><span class="token punctuation">]</span><span class="token operator">:</span> General error<span class="token operator">:</span> <span class="token number">1005</span> Can<span class="token string">'t create table '</span>laravelbootstrapstarter<span class="token punctuation">.</span>#sql<span class="token operator">-</span><span class="token number">42</span>c_f8' <span class="token punctuation">(</span>errno<span class="token operator">:</span> <span class="token number">150</span><span class="token punctuation">)</span>
    <span class="token punctuation">(</span><span class="token constant">SQL</span><span class="token operator">:</span> alter table <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">role_user</span><span class="token template-punctuation string">`</span></span> add constraint role_user_user_id_foreign foreign <span class="token function">key</span> <span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">user_id</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
    references <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">users</span><span class="token template-punctuation string">`</span></span> <span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">id</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">(</span>Bindings<span class="token operator">:</span> <span class="token function">array</span> <span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> 
</code></pre></div><p>很可能是user表中的<code>id</code>列不匹配<code>role_user</code>表<code>user_id</code>列。确保两者都是<code>INT(10)</code>。</p>
<p>当尝试使用EntrustUserTrait方法时，您可能会遇到类似的错误</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>Class name must be a valid object or a string
</code></pre></div><p>那么很可能没有发布过Entrust资源或做了错误的操作。首先检查<code>config</code>目录中是否有<code>entrust.php</code>该文件。如果没有，请尝试执行<code>php artisan vendor:publish</code>，如果依然没有，请手动复制<code>/vendor/zizaco/entrust/src/config/config.php</code>到config目录中并重命名<code>entrust.php</code>。</p>
<p>如果使用自定义命名空间，那么需要修改<code>permission</code>和<code>role</code>模型的位置，可以通过编辑配置文件<code>config/entrust.php</code>来执行此操作</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token string">'role'</span> <span class="token operator">=></span> <span class="token string">'CustomNamespaceRole'</span>
<span class="token string">'permission'</span> <span class="token operator">=></span> <span class="token string">'CustomNamespacepermission'</span>
</code></pre></div></template>
