<template><h1 id="web代理工具对比" tabindex="-1"><a class="header-anchor" href="#web代理工具对比" aria-hidden="true">#</a> Web代理工具对比</h1>
<p><strong>Web代理工具主要应用场景：</strong></p>
<ol>
<li>将线上的静态资源文件（JS、CSS、图片）替换为本地相应的文件，来调试线上（代码都被压缩过）的问题；</li>
<li>本地开发过程，当后端接口未就绪的情况下（也就是前端和后端同学并行开发），将AJAX接口映射于本地文件；</li>
<li>将测试环境或者线上环境的AJAX接口的数据映射于本地，反过来说，也就是开启本地的服务，本地的服务拉取的数据来自测试环境或者线上环境的数据（因为此时测试环境或者线上环境的服务比较稳定，还有，主要此时，测试同学基本都是基于测试环境来注明bug，所以此时可以直接将测试环境的数据来模拟本地拉取的数据，而不是用于自己模拟一套本地数据）</li>
</ol>
<p>上述三个场景比较普遍，需要做代理映射的方面基本在后端服务接口及静态资源（页面代理当然也是可以，只不过场景不多）。</p>
<p><strong>各代理工具的支持情况对比：</strong></p>
<blockquote>
<p>Y: 支持<br>
N: 不支持<br>
Y/N: 不完全支持</p>
</blockquote>
<table>
<thead>
<tr>
<th>需求</th>
<th>Fiddler</th>
<th>Charles</th>
<th>Rythem</th>
<th>TinyProxy</th>
<th>NProxy</th>
</tr>
</thead>
<tbody>
<tr>
<td>支持Mac、Linux以及Windows</td>
<td>Win</td>
<td>Y</td>
<td>Mac&amp;Win</td>
<td>Mac&amp;Linux</td>
<td>Y</td>
</tr>
<tr>
<td>支持HTTP和HTTPS</td>
<td>Y</td>
<td>Y</td>
<td>Y/N</td>
<td>Y</td>
<td>Y</td>
</tr>
<tr>
<td>支持单文件替换</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>N</td>
<td>Y</td>
</tr>
<tr>
<td>支持combo文件替换（即多个文件合并为一个文件的替换）</td>
<td>N</td>
<td>N</td>
<td>Y/N</td>
<td>N</td>
<td>Y</td>
</tr>
<tr>
<td>支持目录替换</td>
<td>Y/N</td>
<td>N</td>
<td>Y</td>
<td>N</td>
<td>Y</td>
</tr>
</tbody>
</table>
</template>
