<template><h1 id="解决mysql-服务器进程-cpu占用100-的问题" tabindex="-1"><a class="header-anchor" href="#解决mysql-服务器进程-cpu占用100-的问题" aria-hidden="true">#</a> 解决MySQL 服务器进程 CPU占用100%的问题</h1>
<h4 id="_1、问题现象描述" tabindex="-1"><a class="header-anchor" href="#_1、问题现象描述" aria-hidden="true">#</a> 1、问题现象描述</h4>
<p>昨天上线一个活动，有个排行榜的功能，刚开始打开很流畅，晚上的时候突然打开很慢，排行榜基本是打不开，猜想估计是服务器出了问题</p>
<h4 id="_2、登录服务器后使用top命令查看资源占用信息" tabindex="-1"><a class="header-anchor" href="#_2、登录服务器后使用top命令查看资源占用信息" aria-hidden="true">#</a> 2、登录服务器后使用top命令查看资源占用信息</h4>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code># top
top <span class="token operator">-</span> <span class="token number">09</span><span class="token operator">:</span><span class="token number">38</span><span class="token operator">:</span><span class="token number">39</span> up <span class="token number">31</span> days<span class="token punctuation">,</span> <span class="token number">16</span><span class="token operator">:</span><span class="token number">48</span><span class="token punctuation">,</span>  <span class="token number">2</span> users<span class="token punctuation">,</span>  load average<span class="token operator">:</span> <span class="token number">0.46</span><span class="token punctuation">,</span> <span class="token number">0.31</span><span class="token punctuation">,</span> <span class="token number">0.25</span>
Tasks<span class="token operator">:</span> <span class="token number">179</span> total<span class="token punctuation">,</span>   <span class="token number">1</span> running<span class="token punctuation">,</span> <span class="token number">178</span> sleeping<span class="token punctuation">,</span>   <span class="token number">0</span> stopped<span class="token punctuation">,</span>   <span class="token number">0</span> zombie
<span class="token operator">%</span><span class="token function">Cpu</span><span class="token punctuation">(</span>s<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token number">391.1</span> us<span class="token punctuation">,</span>  <span class="token number">0.4</span> sy<span class="token punctuation">,</span>  <span class="token number">0.0</span> ni<span class="token punctuation">,</span> <span class="token number">84.1</span> id<span class="token punctuation">,</span>  <span class="token number">0.4</span> wa<span class="token punctuation">,</span>  <span class="token number">0.0</span> hi<span class="token punctuation">,</span>  <span class="token number">0.2</span> si<span class="token punctuation">,</span>  <span class="token number">0.0</span> st
KiB Mem <span class="token operator">:</span> <span class="token number">16267728</span> total<span class="token punctuation">,</span>  <span class="token number">2427980</span> free<span class="token punctuation">,</span>  <span class="token number">2738212</span> used<span class="token punctuation">,</span> <span class="token number">11101536</span> buff<span class="token operator">/</span>cache
KiB Swap<span class="token operator">:</span>  <span class="token number">2097148</span> total<span class="token punctuation">,</span>  <span class="token number">2097148</span> free<span class="token punctuation">,</span>        <span class="token number">0</span> used<span class="token punctuation">.</span> <span class="token number">13136924</span> avail Mem
  <span class="token constant">PID</span> <span class="token constant">USER</span>      <span class="token constant">PR</span>  <span class="token constant">NI</span>    <span class="token constant">VIRT</span>    <span class="token constant">RES</span>    <span class="token constant">SHR</span> <span class="token constant">S</span>  <span class="token operator">%</span><span class="token constant">CPU</span> <span class="token operator">%</span><span class="token constant">MEM</span>     <span class="token constant">TIME</span><span class="token operator">+</span> <span class="token constant">COMMAND</span>
<span class="token number">28739</span> mysql     <span class="token number">20</span>   <span class="token number">0</span> <span class="token number">4111084</span> <span class="token number">875996</span>  <span class="token number">10908</span> <span class="token constant">S</span>  <span class="token number">380.1</span>  <span class="token number">5.4</span>   <span class="token number">1054</span><span class="token operator">:</span><span class="token number">13</span> mysqld 
</code></pre></div><p>果然mysqld进程占用了大部分cpu，因为是4核所以会超过100%，问题定位到mysql数据库</p>
<h4 id="_3、登录mysql查看是否存在查询效率低sql语句" tabindex="-1"><a class="header-anchor" href="#_3、登录mysql查看是否存在查询效率低sql语句" aria-hidden="true">#</a> 3、登录mysql查看是否存在查询效率低sql语句</h4>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>mysql<span class="token operator">></span> show processlist<span class="token punctuation">;</span> 
</code></pre></div><p>反复使用上述命令，发现有一个sql大量出现在列表中</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token constant">SELECT</span>
  a<span class="token punctuation">.</span>openid<span class="token punctuation">,</span>
  b<span class="token punctuation">.</span>nickname<span class="token punctuation">,</span>
  <span class="token constant">COUNT</span><span class="token punctuation">(</span>a<span class="token punctuation">.</span>openid<span class="token punctuation">)</span> <span class="token constant">AS</span> build_count
<span class="token constant">FROM</span>
  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">build</span><span class="token template-punctuation string">`</span></span> <span class="token constant">AS</span> a
  <span class="token constant">LEFT</span> <span class="token constant">JOIN</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">wxuser</span><span class="token template-punctuation string">`</span></span> <span class="token constant">AS</span> b
    <span class="token constant">ON</span> a<span class="token punctuation">.</span>openid <span class="token operator">=</span> b<span class="token punctuation">.</span>openid
<span class="token constant">WHERE</span> lid <span class="token operator">=</span> <span class="token number">1</span>
<span class="token constant">GROUP</span> <span class="token constant">BY</span> a<span class="token punctuation">.</span>openid<span class="token punctuation">,</span>
  b<span class="token punctuation">.</span>nickname<span class="token punctuation">,</span>
  b<span class="token punctuation">.</span>wid
<span class="token constant">ORDER</span> <span class="token constant">BY</span> build_count <span class="token constant">DESC</span><span class="token punctuation">,</span>
  b<span class="token punctuation">.</span>wid <span class="token constant">ASC</span> 
</code></pre></div><p>使用show columns查看表结构</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>mysql<span class="token operator">></span> show columns from build<span class="token punctuation">;</span>
mysql<span class="token operator">></span> show columns from wxuser<span class="token punctuation">;</span> 
</code></pre></div><p>发现问题所在了，wxuser表里openid没有索引，所以马上想到应该增加一个索引</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code>mysql<span class="token operator">></span><span class="token constant">ALTER</span> <span class="token constant">TABLE</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">wxuser</span><span class="token template-punctuation string">`</span></span> <span class="token constant">ADD</span> <span class="token constant">INDEX</span> <span class="token function">ind_openid</span> <span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">openid</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span> 
</code></pre></div><p>由于已经存在大量数据，该sql执行了近23分钟，索引增加完成之后，cpu瞬间下降到1%左右</p>
<h4 id="_4、最后总结" tabindex="-1"><a class="header-anchor" href="#_4、最后总结" aria-hidden="true">#</a> 4、最后总结</h4>
<p><strong>关于优化</strong></p>
<ol>
<li>对 WHERE, JOIN, MAX(), MIN(), ORDER BY 等子句中的条件判断中用到的字段,应该根据其建立索引 INDEX。</li>
<li>增加 tmp_table_size 值。mysql 的配置文件中，tmp_table_size 的默认大小是 32M。如果一张临时表超出该大小，MySQL产生一个 The table tbl_name is full 形式的错误，如果你做很多高级 GROUP BY 查询，增加 tmp_table_size 值。</li>
<li>在开发过程中对于查询比较复杂的sql建议通过EXPLAIN分析SQL语句，并建立索引</li>
</ol>
<p><strong>mysql添加索引命令</strong></p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token number">1.</span><span class="token constant">PRIMARY</span>  <span class="token constant">KEY</span>（主键索引）
mysql<span class="token operator">></span><span class="token constant">ALTER</span>  <span class="token constant">TABLE</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">table_name</span><span class="token template-punctuation string">`</span></span>  <span class="token constant">ADD</span>  <span class="token constant">PRIMARY</span>  <span class="token constant">KEY</span> <span class="token punctuation">(</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">column</span><span class="token template-punctuation string">`</span></span>  <span class="token punctuation">)</span>
<span class="token number">2.</span><span class="token constant">UNIQUE</span><span class="token punctuation">(</span>唯一索引<span class="token punctuation">)</span>
mysql<span class="token operator">></span><span class="token constant">ALTER</span>  <span class="token constant">TABLE</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">table_name</span><span class="token template-punctuation string">`</span></span>  <span class="token constant">ADD</span>  <span class="token constant">UNIQUE</span> <span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">column</span><span class="token template-punctuation string">`</span></span> <span class="token punctuation">)</span>
<span class="token number">3.</span><span class="token constant">INDEX</span><span class="token punctuation">(</span>普通索引<span class="token punctuation">)</span>
mysql<span class="token operator">></span><span class="token constant">ALTER</span>  <span class="token constant">TABLE</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">table_name</span><span class="token template-punctuation string">`</span></span>  <span class="token constant">ADD</span>  <span class="token constant">INDEX</span> <span class="token function">index_name</span> <span class="token punctuation">(</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">column</span><span class="token template-punctuation string">`</span></span>  <span class="token punctuation">)</span>
<span class="token number">4.</span><span class="token constant">FULLTEXT</span><span class="token punctuation">(</span>全文索引<span class="token punctuation">)</span>
mysql<span class="token operator">></span><span class="token constant">ALTER</span>  <span class="token constant">TABLE</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">table_name</span><span class="token template-punctuation string">`</span></span>  <span class="token constant">ADD</span>  <span class="token constant">FULLTEXT</span> <span class="token punctuation">(</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">column</span><span class="token template-punctuation string">`</span></span> <span class="token punctuation">)</span>
<span class="token number">5.</span>多列索引
mysql<span class="token operator">></span><span class="token constant">ALTER</span>  <span class="token constant">TABLE</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">table_name</span><span class="token template-punctuation string">`</span></span>  <span class="token constant">ADD</span>  <span class="token constant">INDEX</span> <span class="token function">index_name</span> <span class="token punctuation">(</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">column1</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">column2</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>  <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">column3</span><span class="token template-punctuation string">`</span></span>  <span class="token punctuation">)</span> 
</code></pre></div><blockquote>
<p>PRIMARY, INDEX, UNIQUE 这3种是一类<br>
PRIMARY 主键。 就是唯一且不能为空<br>
INDEX 索引，普通的<br>
UNIQUE 唯一索引。 不允许有重复<br>
FULLTEXT 是全文索引，用于在一篇文章中，检索文本信息的</p>
</blockquote>
</template>
