<template><h1 id="vue-表单" tabindex="-1"><a class="header-anchor" href="#vue-表单" aria-hidden="true">#</a> Vue 表单</h1>
<p>表单</p>
<ul>
<li>v-model</li>
<li>常见表单项 textarea checkbox radio select</li>
<li>修饰符 lazy number trim</li>
</ul>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>template<span class="token operator">></span>
    <span class="token operator">&lt;</span>div<span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span>输入框<span class="token operator">:</span> <span class="token punctuation">{</span><span class="token punctuation">{</span>name<span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"text"</span> v<span class="token operator">-</span>model<span class="token punctuation">.</span>trim<span class="token operator">=</span><span class="token string">"name"</span><span class="token operator">/</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"text"</span> v<span class="token operator">-</span>model<span class="token punctuation">.</span>lazy<span class="token operator">=</span><span class="token string">"name"</span><span class="token operator">/</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"text"</span> v<span class="token operator">-</span>model<span class="token punctuation">.</span>number<span class="token operator">=</span><span class="token string">"age"</span><span class="token operator">/</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span>多行文本<span class="token operator">:</span> <span class="token punctuation">{</span><span class="token punctuation">{</span>desc<span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
        <span class="token operator">&lt;</span>textarea v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"desc"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>textarea<span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">!</span><span class="token operator">--</span> 注意，<span class="token operator">&lt;</span>textarea<span class="token operator">></span><span class="token punctuation">{</span><span class="token punctuation">{</span>desc<span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>textarea<span class="token operator">></span> 是不允许的！！！ <span class="token operator">--</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span>复选框 <span class="token punctuation">{</span><span class="token punctuation">{</span>checked<span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"checkbox"</span> v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"checked"</span><span class="token operator">/</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span>多个复选框 <span class="token punctuation">{</span><span class="token punctuation">{</span>checkedNames<span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"checkbox"</span> id<span class="token operator">=</span><span class="token string">"jack"</span> value<span class="token operator">=</span><span class="token string">"Jack"</span> v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"checkedNames"</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>label <span class="token keyword">for</span><span class="token operator">=</span><span class="token string">"jack"</span><span class="token operator">></span>Jack<span class="token operator">&lt;</span><span class="token operator">/</span>label<span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"checkbox"</span> id<span class="token operator">=</span><span class="token string">"john"</span> value<span class="token operator">=</span><span class="token string">"John"</span> v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"checkedNames"</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>label <span class="token keyword">for</span><span class="token operator">=</span><span class="token string">"john"</span><span class="token operator">></span>John<span class="token operator">&lt;</span><span class="token operator">/</span>label<span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"checkbox"</span> id<span class="token operator">=</span><span class="token string">"mike"</span> value<span class="token operator">=</span><span class="token string">"Mike"</span> v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"checkedNames"</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>label <span class="token keyword">for</span><span class="token operator">=</span><span class="token string">"mike"</span><span class="token operator">></span>Mike<span class="token operator">&lt;</span><span class="token operator">/</span>label<span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span>单选 <span class="token punctuation">{</span><span class="token punctuation">{</span>gender<span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"radio"</span> id<span class="token operator">=</span><span class="token string">"male"</span> value<span class="token operator">=</span><span class="token string">"male"</span> v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"gender"</span><span class="token operator">/</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>label <span class="token keyword">for</span><span class="token operator">=</span><span class="token string">"male"</span><span class="token operator">></span>男<span class="token operator">&lt;</span><span class="token operator">/</span>label<span class="token operator">></span>
        <span class="token operator">&lt;</span>input type<span class="token operator">=</span><span class="token string">"radio"</span> id<span class="token operator">=</span><span class="token string">"female"</span> value<span class="token operator">=</span><span class="token string">"female"</span> v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"gender"</span><span class="token operator">/</span><span class="token operator">></span>
        <span class="token operator">&lt;</span>label <span class="token keyword">for</span><span class="token operator">=</span><span class="token string">"female"</span><span class="token operator">></span>女<span class="token operator">&lt;</span><span class="token operator">/</span>label<span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span>下拉列表选择 <span class="token punctuation">{</span><span class="token punctuation">{</span>selected<span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
        <span class="token operator">&lt;</span>select v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"selected"</span><span class="token operator">></span>
            <span class="token operator">&lt;</span>option disabled value<span class="token operator">=</span><span class="token string">""</span><span class="token operator">></span>请选择<span class="token operator">&lt;</span><span class="token operator">/</span>option<span class="token operator">></span>
            <span class="token operator">&lt;</span>option<span class="token operator">></span><span class="token constant">A</span><span class="token operator">&lt;</span><span class="token operator">/</span>option<span class="token operator">></span>
            <span class="token operator">&lt;</span>option<span class="token operator">></span><span class="token constant">B</span><span class="token operator">&lt;</span><span class="token operator">/</span>option<span class="token operator">></span>
            <span class="token operator">&lt;</span>option<span class="token operator">></span><span class="token constant">C</span><span class="token operator">&lt;</span><span class="token operator">/</span>option<span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">/</span>select<span class="token operator">></span>
        <span class="token operator">&lt;</span>p<span class="token operator">></span>下拉列表选择（多选） <span class="token punctuation">{</span><span class="token punctuation">{</span>selectedList<span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>p<span class="token operator">></span>
        <span class="token operator">&lt;</span>select v<span class="token operator">-</span>model<span class="token operator">=</span><span class="token string">"selectedList"</span> multiple<span class="token operator">></span>
            <span class="token operator">&lt;</span>option disabled value<span class="token operator">=</span><span class="token string">""</span><span class="token operator">></span>请选择<span class="token operator">&lt;</span><span class="token operator">/</span>option<span class="token operator">></span>
            <span class="token operator">&lt;</span>option<span class="token operator">></span><span class="token constant">A</span><span class="token operator">&lt;</span><span class="token operator">/</span>option<span class="token operator">></span>
            <span class="token operator">&lt;</span>option<span class="token operator">></span><span class="token constant">B</span><span class="token operator">&lt;</span><span class="token operator">/</span>option<span class="token operator">></span>
            <span class="token operator">&lt;</span>option<span class="token operator">></span><span class="token constant">C</span><span class="token operator">&lt;</span><span class="token operator">/</span>option<span class="token operator">></span>
        <span class="token operator">&lt;</span><span class="token operator">/</span>select<span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">/</span>template<span class="token operator">></span>
<span class="token operator">&lt;</span>script<span class="token operator">></span>
<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">{</span>
    <span class="token function">data</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token punctuation">{</span>
            name<span class="token operator">:</span> <span class="token string">'双越'</span><span class="token punctuation">,</span>
            age<span class="token operator">:</span> <span class="token number">18</span><span class="token punctuation">,</span>
            desc<span class="token operator">:</span> <span class="token string">'自我介绍'</span><span class="token punctuation">,</span>
            checked<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
            checkedNames<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
            gender<span class="token operator">:</span> <span class="token string">'male'</span><span class="token punctuation">,</span>
            selected<span class="token operator">:</span> <span class="token string">''</span><span class="token punctuation">,</span>
            selectedList<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token operator">&lt;</span><span class="token operator">/</span>script<span class="token operator">></span>
</code></pre></div></template>
