<template><h1 id="判断字符串以字母开头-后面字母数字下划线-长度-6-30" tabindex="-1"><a class="header-anchor" href="#判断字符串以字母开头-后面字母数字下划线-长度-6-30" aria-hidden="true">#</a> 判断字符串以字母开头，后面字母数字下划线，长度 6-30</h1>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> reg1 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token string">'^[a-zA-Z]\\w{5,29}$'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> reg2 <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^[a-zA-Z]\w{5,29}$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
<span class="token keyword">const</span> str <span class="token operator">=</span> <span class="token string">'A123456'</span><span class="token punctuation">;</span>
console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>reg1<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span>
console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>reg2<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre></div><p>一些简单的</p>
<div class="language-javascript ext-js"><pre v-pre class="language-javascript"><code><span class="token comment">// 邮政编码 6位数字</span>
<span class="token operator">/</span>\d<span class="token punctuation">{</span><span class="token number">6</span><span class="token punctuation">}</span><span class="token operator">/</span>
<span class="token comment">// 小写英文字母</span>
<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z<span class="token punctuation">]</span><span class="token operator">+</span>$<span class="token operator">/</span>
<span class="token comment">// 英文字母</span>
<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">[</span>a<span class="token operator">-</span>zA<span class="token operator">-</span>z<span class="token punctuation">]</span><span class="token operator">+</span>$<span class="token operator">/</span>
<span class="token comment">// 日期格式 2020-11-04</span>
<span class="token operator">/</span><span class="token operator">^</span>\d<span class="token punctuation">{</span><span class="token number">4</span><span class="token punctuation">}</span><span class="token operator">-</span>\d<span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">}</span><span class="token operator">-</span>\d<span class="token punctuation">{</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">}</span>$<span class="token operator">/</span>
<span class="token comment">// 用户名，字母开头</span>
<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">[</span>a<span class="token operator">-</span>zA<span class="token operator">-</span>z<span class="token punctuation">]</span>\w<span class="token punctuation">{</span><span class="token number">5</span><span class="token punctuation">,</span><span class="token number">17</span><span class="token punctuation">}</span>$<span class="token operator">/</span>
<span class="token comment">// 简单的 ip 地址匹配</span>
<span class="token operator">/</span>\d<span class="token operator">+</span><span class="token punctuation">.</span>\d<span class="token operator">+</span><span class="token punctuation">.</span>\d<span class="token operator">+</span><span class="token punctuation">.</span>\d<span class="token operator">+</span><span class="token operator">/</span>
</code></pre></div></template>
